# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awrit < Formula
  desc "Chromium-based browser that renders in Kitty"
  homepage "https://github.com/chase/awrit"
  version "1.0.0"
  license "BSD"

  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chase/awrit/releases/download/v#{version}/awrit-mac-arm64.tar.xz"
      sha256 `curl -Ls "https://github.com/chase/awrit/releases/download/v#{version}/awrit-mac-arm64.tar.xz.sha256sum"`.split.first
    elsif Hardware::CPU.intel?
      url "https://github.com/chase/awrit/releases/download/v#{version}/awrit-mac-x86_64.tar.xz"
      sha256 `curl -Ls "https://github.com/chase/awrit/releases/download/v#{version}/awrit-mac-x86_64.tar.xz.sha256sum"`.split.first
    end

    def install
      prefix.install "lib/awrit/awrit.app"
      bin.write_exec_script "#{prefix}/awrit.app/Contents/MacOS/awrit"
    end
  end

  depends_on :macos => :monterey

  def caveats
    <<~EOS

You can ignore any errors above that start with:

- Failed changing dylib ID
- Failed to fix install linkage

Please do not report this as an issue on GitHub. Homebrew is not smart and there is no way to prevent this.
    EOS
  end
end
